# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
#
# The pages under docs/source/ are generated by src/generate_docs.py from the catalog data in
# .working/ and the curated tables in data/. This file configures how Sphinx renders
# them; it documents no Python API, so the autodoc family of extensions is not loaded.

from datetime import date

# -- Project information -----------------------------------------------------

project = "HED task catalog"
copyright = f"2026-{date.today().year}, HED Working Group"
author = "HED Working Group"
release = "1.0.0"

# -- General configuration ---------------------------------------------------

extensions = [
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "_templates", "Thumbs.db", ".DS_Store"]
source_suffix = {".md": "markdown"}
master_doc = "index"

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_title = "HED task catalog"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_js_files = ["gh_icon_fix.js"]
html_logo = "_static/images/croppedWideLogo.png"

# There is no Python domain content, so py-modindex.html would be empty.
html_domain_indices = False

html_theme_options = {
    # The brand template in _templates/sidebar/brand.html prints the site name under
    # the logo, so Furo's own copy is hidden.
    "sidebar_hide_name": True,
    "light_css_variables": {
        "color-brand-primary": "#0969da",
        "color-brand-content": "#0969da",
    },
    "dark_css_variables": {
        "color-brand-primary": "#58a6ff",
        "color-brand-content": "#58a6ff",
    },
    "source_repository": "https://github.com/hed-standard/hed-task/",
    "source_branch": "main",
    "source_directory": "docs/source/",
}

# Same sidebar composition as hed-resources: brand, search, navigation, quick links.
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "quicklinks.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
    ]
}

# -- MyST parser settings ----------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "tasklist",
]

# Process pages use (hed-xxx)= Sphinx labels as anchor targets for deep links from
# task pages, which render correctly in HTML as <span id="hed-xxx">. MyST's link
# validator does not recognise MyST labels as valid local IDs (it only checks
# myst_heading_anchors slugs), so it reports myst.xref_missing even though browser
# navigation works.
suppress_warnings = ["myst.xref_missing"]
